enum IrNodeType {
  literal('literal'),
  constNode('const'),
  ref('ref'),
  actionSequence('actionSequence'),
  event('event'),
  widget('widget'),
  builtin('builtin'),
  list('list'),
  map('map'),
  record('record'),
  cond('cond'),
  forNode('for'),
  spread('spread'),
  cmp('cmp'),
  arith('arith'),
  logic('logic'),
  not('not'),
  coalesce('coalesce'),
  getter('getter'),
  setterCall('setterCall'),
  let('let'),
  assign('assign'),
  sequence('sequence'),
  lambda('lambda'),
  member('member'),
  indexNode('index'),
  length('length'),
  isnull('isnull'),
  isType('isType'),
  asType('asType'),
  runtimeTypeRef('runtimeTypeRef'),
  interp('interp'),
  methodCall('MethodCall'),
  valueCtor('ValueCtor'),
  block('block'),
  ifStmt('ifStmt'),
  breakNode('break'),
  continueNode('continue'),
  returnStmt('returnStmt'),
  letStmt('letStmt'),
  whileNode('while'),
  doNode('do'),
  imperativeFor('imperativeFor'),
  stateful('stateful'),
  statefulField('statefulField'),
  payloadClass('payloadClass'),
  payloadField('payloadField'),
  payloadCtor('payloadCtor'),
  payloadFieldInit('payloadFieldInit'),
  payloadInstanceCreate('payloadInstanceCreate'),
  payloadFn('payloadFn'),
  payloadFnCall('payloadFnCall'),
  payloadMethodCall('payloadMethodCall'),
  payloadFieldRef('payloadFieldRef'),
  payloadFieldAssign('payloadFieldAssign'),
  thisFieldRef('thisFieldRef'),
  thisRef('thisRef'),
  payloadMixin('payloadMixin'),
  payloadExtension('payloadExtension'),
  payloadFnValue('payloadFnValue'),
  screenWithFunctions('screenWithFunctions'),
  actionStep('actionStep'),
  tryStep('tryStep');

  final String wireName;

  const IrNodeType(this.wireName);

  static final Map<String, IrNodeType> _byName = {
    for (final value in IrNodeType.values) value.wireName: value,
  };

  static IrNodeType? fromWireName(String name) => _byName[name];
}
